export const tableData = [
  {
    id: 1,
    name: "Protein Bar 100g",
    sales: 93132.12,
    outOfStock: 1.68,
    totalInventory: 931.9,
    stockLevel: 87,
    daysOfSupply: 23,
    reorderPoint: 15,
    retailPrice: 129.99,
    avgRank: 3.2,
    estTraffic: 12303,
    estImpressions: 25005,
    ctr: 1.9,
    conversionRate: 3.2,
    avgSessionDuration: 143,
    bounceRate: 28.5,
    searchVisibility: 72.4,
    productRanking: 4,
  },
  {
    id: 2,
    name: "Choco Bar 100g",
    sales: 8526.32,
    outOfStock: 6.79,
    totalInventory: 679,
    stockLevel: 65,
    daysOfSupply: 18,
    reorderPoint: 20,
    retailPrice: 89.99,
    avgRank: 7,
    estTraffic: 3005,
    estImpressions: 4231,
    ctr: 2.4,
    conversionRate: 2.8,
    avgSessionDuration: 127,
    bounceRate: 32.1,
    searchVisibility: 68.9,
    productRanking: 8,
    growth: 2.4,
  },
  {
    id: 3,
    name: "SKU 3",
    sales: 9313,
    outOfStock: 1.68,
    totalInventory: 931.9,
    stockLevel: 54,
    daysOfSupply: 14,
    reorderPoint: 25,
    retailPrice: 149.99,
    avgRank: 11,
    estTraffic: 1931.9,
    estImpressions: 931.9,
    ctr: 1.9,
    conversionRate: 1.5,
    avgSessionDuration: 98,
    bounceRate: 38.7,
    searchVisibility: 54.3,
    productRanking: 12,
  },
  {
    id: 4,
    name: "SKU 4",
    sales: 0,
    outOfStock: 0,
    totalInventory: 0,
    stockLevel: 0,
    daysOfSupply: 0,
    reorderPoint: 0,
    retailPrice: 0,
    avgRank: 0,
    estTraffic: 0,
    estImpressions: 0,
    ctr: 0,
    conversionRate: 0,
    avgSessionDuration: 0,
    bounceRate: 0,
    searchVisibility: 0,
    productRanking: 0,
  },
];

// SKU Totals
export const totals = {
  sales: 293132.12,
  outOfStock: 16,
  totalInventory: 2931,
  stockLevel: 206,
  daysOfSupply: 55,
  reorderPoint: 60,
  retailPrice: 369.97,
  avgRank: 8.3,
  estTraffic: 61985,
  estImpressions: 261768,
  ctr: 1.9,
  conversionRate: 2.5,
  avgSessionDuration: 122,
  bounceRate: 33.1,
  searchVisibility: 65.2,
  productRanking: 8,
};

export const columns = [
  { id: "name", label: "SKU Name", hasIcon: true },
  { id: "sales", label: "Sales", section: "Availability", type: "currency" },
  {
    id: "outOfStock",
    label: "Out of Stock",
    section: "Availability",
    type: "percentage",
  },
  {
    id: "totalInventory",
    label: "Total Inventory",
    section: "Availability",
    type: "number",
  },
  {
    id: "stockLevel",
    label: "Stock Level",
    section: "Availability",
    type: "number",
  },
  {
    id: "daysOfSupply",
    label: "Days of Supply",
    section: "Availability",
    type: "number",
  },
  {
    id: "reorderPoint",
    label: "Reorder Point",
    section: "Availability",
    type: "number",
  },
  {
    id: "retailPrice",
    label: "Retail Price",
    section: "Availability",
    type: "currency",
  },
  // Visibility Columns
  {
    id: "avgRank",
    label: "Average Rank",
    section: "Visibility",
    type: "number",
  },
  {
    id: "estTraffic",
    label: "Est. Traffic",
    section: "Visibility",
    type: "number",
  },
  {
    id: "estImpressions",
    label: "Est. Impressions",
    section: "Visibility",
    type: "number",
  },
  { id: "ctr", label: "CTR", section: "Visibility", type: "percentage" },
  {
    id: "conversionRate",
    label: "Conversion Rate",
    section: "Visibility",
    type: "percentage",
  },
  {
    id: "avgSessionDuration",
    label: "Avg. Session",
    section: "Visibility",
    type: "number",
  },
  {
    id: "bounceRate",
    label: "Bounce Rate",
    section: "Visibility",
    type: "percentage",
  },
  {
    id: "searchVisibility",
    label: "Search Visibility",
    section: "Visibility",
    type: "percentage",
  },
  {
    id: "productRanking",
    label: "Product Ranking",
    section: "Visibility",
    type: "number",
  },
];

export const cityTableData = [
  {
    id: 1,
    name: "Delhi",
    sales: 125000,
    outOfStock: 3.2,
    totalInventory: 560,
    stockLevel: 78,
    daysOfSupply: 12,
    reorderPoint: 8,
    retailPrice: 145.5,
    avgRank: 2.5,
    estTraffic: 15000,
    estImpressions: 30000,
    ctr: 2.1,
    conversionRate: 2.2,
    avgSessionDuration: 134,
    bounceRate: 27.5,
    searchVisibility: 70.5,
    productRanking: 5,
  },
  {
    id: 2,
    name: "Mumbai",
    sales: 98000,
    outOfStock: 5.1,
    totalInventory: 820,
    stockLevel: 64,
    daysOfSupply: 15,
    reorderPoint: 10,
    retailPrice: 139.99,
    avgRank: 4.0,
    estTraffic: 12000,
    estImpressions: 28000,
    ctr: 1.8,
    conversionRate: 2.0,
    avgSessionDuration: 125,
    bounceRate: 29.0,
    searchVisibility: 68.0,
    productRanking: 7,
  },
  {
    id: 3,
    name: "Bengaluru",
    sales: 87000,
    outOfStock: 2.5,
    totalInventory: 700,
    stockLevel: 70,
    daysOfSupply: 13,
    reorderPoint: 9,
    retailPrice: 134.99,
    avgRank: 3.0,
    estTraffic: 10000,
    estImpressions: 25000,
    ctr: 2.0,
    conversionRate: 2.5,
    avgSessionDuration: 115,
    bounceRate: 30.5,
    searchVisibility: 66.0,
    productRanking: 6,
  },
  {
    id: 4,
    name: "Chennai",
    sales: 65000,
    outOfStock: 4.0,
    totalInventory: 400,
    stockLevel: 50,
    daysOfSupply: 11,
    reorderPoint: 7,
    retailPrice: 120.0,
    avgRank: 6.0,
    estTraffic: 8000,
    estImpressions: 20000,
    ctr: 1.7,
    conversionRate: 2.0,
    avgSessionDuration: 110,
    bounceRate: 33.0,
    searchVisibility: 64.0,
    productRanking: 8,
  },
];

export const cityTotals = {
  sales: 223000,
  outOfStock: 8.3,
  totalInventory: 2500,
  stockLevel: 262,
  daysOfSupply: 51,
  reorderPoint: 35,
  retailPrice: 540.48,
  avgRank: 15.5,
  estTraffic: 45000,
  estImpressions: 103000,
  ctr: 7.0,
  conversionRate: 8.7,
  avgSessionDuration: 484,
  bounceRate: 120.0,
  searchVisibility: 268.5,
  productRanking: 26,
};
